### ISSUE TITLE
Ability to account for days schedueled differently.

### ISSUE THREAD

**Issue by averycblack** [jeffrypig23/SGSClassCountdown#1]
Idk how your school works, but like when certain days have assemblies or something.

Also, been way to long since we've talked :P

**Comment by yeSpud** [comment]
Yikes, its been a while since I've given this project any attention.

26th of October? *Its really been that long?*



While the original plan for this app was to make it fit my school's specific schedule, I realize that not only is it likely that they'll change schedules in the future. So, making this app easily adaptable for other school's schedules isn't a bad idea either.

So I will work on adding a way to create custom periods for things like assemblies/pep-rallies/after-school clubs (*\*cough\* robotics \*cough\**) , which will not only comply with your feature request, but also add general flexibility, and even help future proof it.

**Comment by yeSpud** [comment]
Yeah its been a while since we last talked. You got some form of social that [I can contact you from](mailto:stephenogden01@gmail.com)? ;)

**Comment by averycblack** [comment]
Contact me via email and we can continue this.  
avery.c.black@gmail.com

**Comment by yeSpud** [comment]
So technically this has been achieved, and the alpha build is live (if you want a link let me know), but there are a bunch of UI bugs that need to be fixed.

However, since the request has been met I'm closing the issue.
